services:
  db:
    image: postgres:15
    container_name: poklet-db
    restart: unless-stopped
    env_file:
      - ./env/.env.full
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    networks:
      - poklet-net

  backend:
    build:
      context: ../backend
    container_name: poklet-backend
    restart: unless-stopped
    env_file:
      - ./env/.env.full
    depends_on:
      - db
    volumes:
      - ../backend:/app
      - ./env/.env.full:/app/.env
    networks:
      - poklet-net
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "

  frontend:
    build:
      context: ../frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
      dockerfile: Dockerfile
    container_name: poklet-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - poklet-net

  backend-nginx:
    image: nginx:1.25
    container_name: poklet-backend-nginx
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ../backend/staticfiles:/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - poklet-net

networks:
  poklet-net:
    driver: bridge
