services:
  db-dev:
    image: postgres:15
    container_name: poklet-dev-db
    restart: unless-stopped
    env_file:
      - ./env/.env.dev
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db/dev_postgres:/var/lib/postgresql/data
    networks:
      - poklet-dev-net

networks:
  poklet-dev-net:
    driver: bridge
