# Generated by Django 5.2.1 on 2025-06-03 14:57

import uuid

import django.db.models.deletion
from django.db import migrations, models

import app.sessions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "short_id",
                    models.CharField(
                        default=app.sessions.models.generate_short_id,
                        editable=False,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revealed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_id", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=50)),
                ("vote", models.CharField(blank=True, max_length=10, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="app.session",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "client_id"), ("session", "name")},
            },
        ),
    ]
